### PR TITLE
expires -> expiresAt; min express-session and prisma versions

### PR DESCRIPTION
**Pull request by kleydon**
This PR...

* Renames `expires` to `expiresAt`, to match Prisma's naming convention for dates
* Sets minimum version numbers for `prisma` and `express-session` peer dependencies
* Updates documentation accordingly
* Updates several package dependencies

### CODE REVIEW

**Comment by kleydon** [comment]
@wSedlacek 3rd times a charm (hopefully). With this PR, I believe the commit messages are now in the right format, and I've additionally added `>=` version checks for `prisma` and `express-session`.

See what you think.

**Review by wSedlacek — APPROVED** [review]
LGTM

**Comment by wSedlacek** [comment]
Automatic releases are so cool 🎉

**Pull request merged**
