### PR TITLE
Recovery from invalid connection

### PR DESCRIPTION
**Pull request by ka2n**
Hello,

This pull request addresses an issue where PrismaSessionStore does not recover after an initial failed connection, even when Prisma later connects successfully. The fix implements a recovery process once validateConnection subsequently succeeds.

Thank you.

### CODE REVIEW

**Comment by kleydon** [comment]
Thanks for the contribution!
I'm currently on the road, but will check it out over the next week.

**Review by kleydon — APPROVED** [review]
Looks good, as far as I can tell.

**Comment by kleydon** [comment]
Just merged into master; thanks again for the fix.

**Comment by ka2n** [comment]
@kleydon Thank you!!

**Pull request merged**
