### PR TITLE
revert: v1.1.0 release

### PR DESCRIPTION
**Pull request by wSedlacek**
This reverts commit 239b192378944f37a4d082adb88e9fcffdb8ce04.

### CODE REVIEW

**Comment by wSedlacek** [comment]
Screen Shot 2020-09-12 at 19 30 06
Still need to remove this tag

**Review by kleydon — COMMENTED** [review]
👍

**Review by kleydon — COMMENTED** [review]
👍

**Comment by kleydon** [comment]
I think we each closed each other's identical PR. Re-opening this one...

**Review by kleydon — APPROVED** [review]
Approved.

**Pull request merged**
