### PR TITLE
fix: changed findOne to findUnique, for Prisma 2.12.0+

### PR DESCRIPTION
**Pull request by kleydon**
* Prisma to 2.12.0
* findOne() -> findUnique(), see https://github.com/prisma/prisma/releases/tag/2.12.0
* Readme - minor fixes

fixes: #25

### CODE REVIEW

**Comment by kleydon** [comment]
@wSedlacek, would you mind taking a look at this?

**Comment by wSedlacek** [comment]
> @wSedlacek, would you mind taking a look at this?

LGTM. The nice part about having 100% test coverage is that if the test pass with the updated version then I can be pretty confident that it works.

**Review by wSedlacek — APPROVED** [review]

**Comment by kleydon** [comment]
Thanks!

**Comment by wSedlacek** [comment]
One thing I am noticing after the fact is that in the change log this shows up as a bug fix
In the future updates like these should be a `chore`

**Pull request merged**
