### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by wSedlacek**
## Description

This updates the dependencies and dev dependencies to the latest version at time of writing
This updates husky to the new format introduced in husky 7
This moves `prisma` from being a dependency to a devDependency as `@prisma/client` is already a peerDependency﻿
This configures `ts-jest` to explicitly use the `tsconfig.spec.json`
This configures testing to allow `es2019` so that `Object.fromEntries` can be used.
This updates the GitHub Actions to run with node 14.x

### CODE REVIEW

**Comment by wSedlacek** [comment]
@kleydon Let's hold off on merging this until we have confirmed the results of the requested test of #62

**Comment by kleydon** [comment]
👍

**Comment by simontaisne** [comment]
Any news on that? It's getting tricky to upgrade to Prisma 3 when using `prisma-session-store`.

**Comment by kleydon** [comment]
Hi @wSedlacek,

>>Let's hold off on merging this until we have confirmed the results of the requested test of #62 (comment)

Do you still see value in waiting? 
(I'm weighing whether to merge this, vs. create another PR & release that moves prisma to a dev dependency...)

-K

**Comment by wSedlacek** [comment]
It's been enough time, let's get this merged in.

**Review by kleydon — APPROVED** [review]

**Comment by kleydon** [comment]
@wSedlacek - Merged this PR ~5min ago, but am forgetting: 
Should merging have _automatically_ generated a new release / npm package version? Or are additional steps necessary?
Thanks,
-K

**Comment by wSedlacek** [comment]
The release will only occur if there are `feat` or `fix` commits.
Since this was a `chore` no release occurred.

**Comment by kleydon** [comment]
@wSedlacek - To attempt to trigger a new release, I've:

1) Created a [fix commit](https://github.com/kleydon/prisma-session-store/pull/66/commits/39d1a56069b770845c8a28af76266d1d1c92b7e1) on a [new branch](https://github.com/kleydon/prisma-session-store/tree/dev-1) (the commit content being trivial changes to the README)
2) Merge the new branch into master.

So far, though, it _looks_ like no new release / package version has been triggered.

Any recommendations re: what to do differently, how to diagnose, or how to 'manually' kick off a release / NPM update?

**Comment by wSedlacek** [comment]
The most recent release failed because the commit failed to pass commitlint:
```
✖   footer's lines must not be longer than 100 characters [footer-max-line-length]
```

https://github.com/conventional-changelog/commitlint/blob/e7a6a7ac1b2179b3c1896957b4a6c4c0b68ec6f4/%40commitlint/config-conventional/index.js#L8

I recommend making another PR to change this setting from a `error` to a `warning` so that the generated commits do not fail because of it.

**Comment by kleydon** [comment]
Thanks!

**Comment by kleydon** [comment]
@simontaisne
>Any news on that? It's getting tricky to upgrade to Prisma 3 when using prisma-session-store.
Just updated the npm package; things should be fixed now...

**Comment by simontaisne** [comment]
Awesome! Thanks for the new release 💯

**Comment by kleydon** [comment]
👍

**Pull request merged**
